### PR TITLE
Qianruo's reinforcement learning note added

### PR DESCRIPTION
**Pull request by Genieeett**

### CODE REVIEW

**Comment by Genieeett** [comment]
format refined

**Comment by Genieeett** [comment]
Reinforcement learning notes refined

**Comment by jun-yan** [comment]
The code chunks run smoothly on my computer, which is good.

There are several code chunks without surrounding text to explain the code. This does not fit the style of the notes. Please add sufficient surrounding texts.

**Comment by Genieeett** [comment]
Dear professor,

I'm Qianruo, I just added the reinforcement learning notes into the new document. And create a new pull request. Please check if there's anything else need to be done.

Qianruo Tan
________________________________

**Pull request closed without merging**
